In [8]:
import numpy as np
np.array([5,9,13,15,16,13,12])

array([ 5,  9, 13, 15, 16, 13, 12])

In [9]:
type([5,9,13,15,16,13,12])

list

In [6]:
import numpy as np

array= np.array([5,9,13,15,16,13,12])
print(array)

[ 5  9 13 15 16 13 12]


In [10]:
type(array.dtype)

numpy.dtype[int64]

In [22]:
# TWO DIMENSIONAL


arg = np.array([[2,3],[4,5],[5,6],[6,8],[8,9]])

print ("TYPE  - ", arg.dtype)

print("\n", "*" * 50)

print("\n", a)

TYPE  -  int64

 **************************************************

 [[2 3]
 [4 5]
 [5 6]
 [6 8]
 [8 9]]


In [24]:
# data type conversion

np.array([1,2,3,4,5,6], dtype= float)

array([1., 2., 3., 4., 5., 6.])

In [26]:
# creating array using .mat   (matrix)


np.array(np.mat("1 2 3 4 5 ; 6 7 8 8 9"))

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 8, 9]])

In [28]:
# converting list into array:


list= [1,2,3,4,5]
array= np.array(list)
print(array)

[1 2 3 4 5]


In [30]:
# copy array into other:


array1= np.asarray(array)
print(array1)

[1 2 3 4 5]


In [42]:
# DATA TYPES  :::::::



my_mat=[[1,2,3,],[4,5,6],[7,8,9],[3,5,7]]
mat= np.array(my_mat)



print(mat)

print(" \n print type/class of this object: ", type(mat) )

print(" \n here is the matrix \n-------------\n",mat,"\n------------")

print("\n dimension of this matrix: ",mat.ndim, sep="")

print("\n size of this matrix: ",mat.size,sep="") # gives the total numbers of the matrix elements 


print("\n shape of this matrix: ",mat.shape)


print("\n data type of this matrix: ",mat.dtype)


[[1 2 3]
 [4 5 6]
 [7 8 9]
 [3 5 7]]
 
 print type/class of this object:  <class 'numpy.ndarray'>
 
 here is the matrix 
-------------
 [[1 2 3]
 [4 5 6]
 [7 8 9]
 [3 5 7]] 
------------

 dimension of this matrix: 2

 size of this matrix: 12

 shape of this matrix:  (4, 3)

 data type of this matrix:  int64


In [49]:
# arange and linspace:::::::

# don't work with python range  ( in python we can't generate the flote numbers in range i.e the limitation in the python.)
list[range(2,10)]


TypeError: list indices must be integers or slices, not range

In [50]:
a= np.arange(2,10.5,.4)
print(a)

[ 2.   2.4  2.8  3.2  3.6  4.   4.4  4.8  5.2  5.6  6.   6.4  6.8  7.2
  7.6  8.   8.4  8.8  9.2  9.6 10.  10.4]


In [51]:
# reverse order:::


a[::-1]

array([10.4, 10. ,  9.6,  9.2,  8.8,  8.4,  8. ,  7.6,  7.2,  6.8,  6.4,
        6. ,  5.6,  5.2,  4.8,  4.4,  4. ,  3.6,  3.2,  2.8,  2.4,  2. ])

In [59]:
print("Every 5th number from 50 in the reverse order : ",np.arange(50,0,-5))


print("\n linearly spaced numbers 1 to 5 \n------------","\n",np.linspace(10,45,5),"\n--------------")

Every 5th number from 50 in the reverse order :  [50 45 40 35 30 25 20 15 10  5]

 linearly spaced numbers 1 to 5 
------------ 
 [10.   18.75 27.5  36.25 45.  ] 
--------------


In [ ]:
a=