In [2]:
import numpy as np
np.array([5,9,13,15,16,13,12])

array([ 5,  9, 13, 15, 16, 13, 12])

In [3]:
type([5,9,13,15,16,13,12])

list

In [4]:
import numpy as np

array= np.array([5,9,13,15,16,13,12])
print(array)

[ 5  9 13 15 16 13 12]


In [5]:
type(array.dtype)

numpy.dtype[int64]

In [6]:
# TWO DIMENSIONAL


arg = np.array([[2,3],[4,5],[5,6],[6,8],[8,9]])

print ("TYPE  - ", arg.dtype)

print("\n", "*" * 50)

print("\n", a)

TYPE  -  int64

 **************************************************


NameError: name 'a' is not defined

In [7]:
# data type conversion

np.array([1,2,3,4,5,6], dtype= float)

array([1., 2., 3., 4., 5., 6.])

In [8]:
# creating array using .mat   (matrix)


np.array(np.mat("1 2 3 4 5 ; 6 7 8 8 9"))

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 8, 9]])

In [9]:
# converting list into array:


list= [1,2,3,4,5]
array= np.array(list)
print(array)

[1 2 3 4 5]


In [10]:
# copy array into other:


array1= np.asarray(array)
print(array1)

[1 2 3 4 5]


In [11]:
# DATA TYPES  :::::::



my_mat=[[1,2,3,],[4,5,6],[7,8,9],[3,5,7]]
mat= np.array(my_mat)



print(mat)

print(" \n print type/class of this object: ", type(mat) )

print(" \n here is the matrix \n-------------\n",mat,"\n------------")

print("\n dimension of this matrix: ",mat.ndim, sep="")

print("\n size of this matrix: ",mat.size,sep="") # gives the total numbers of the matrix elements 


print("\n shape of this matrix: ",mat.shape)


print("\n data type of this matrix: ",mat.dtype)


[[1 2 3]
 [4 5 6]
 [7 8 9]
 [3 5 7]]
 
 print type/class of this object:  <class 'numpy.ndarray'>
 
 here is the matrix 
-------------
 [[1 2 3]
 [4 5 6]
 [7 8 9]
 [3 5 7]] 
------------

 dimension of this matrix: 2

 size of this matrix: 12

 shape of this matrix:  (4, 3)

 data type of this matrix:  int64


In [12]:
# arange and linspace:::::::

# don't work with python range  ( in python we can't generate the flote numbers in range i.e the limitation in the python.)
list[range(2,10)]


TypeError: list indices must be integers or slices, not range

In [13]:
a= np.arange(2,10.5,.4)
print(a)

[ 2.   2.4  2.8  3.2  3.6  4.   4.4  4.8  5.2  5.6  6.   6.4  6.8  7.2
  7.6  8.   8.4  8.8  9.2  9.6 10.  10.4]


In [14]:
# reverse order:::


a[::-1]

array([10.4, 10. ,  9.6,  9.2,  8.8,  8.4,  8. ,  7.6,  7.2,  6.8,  6.4,
        6. ,  5.6,  5.2,  4.8,  4.4,  4. ,  3.6,  3.2,  2.8,  2.4,  2. ])

In [15]:
print("Every 5th number from 50 in the reverse order : ",np.arange(50,0,-5))


print("\n linearly spaced numbers 1 to 5 \n------------","\n",np.linspace(10,45,5),"\n--------------")

Every 5th number from 50 in the reverse order :  [50 45 40 35 30 25 20 15 10  5]

 linearly spaced numbers 1 to 5 
------------ 
 [10.   18.75 27.5  36.25 45.  ] 
--------------


In [21]:
# include endpoint and check space between the points:::

# by default endpooint=true

# byfault retstep= false
import numpy as np

np.linspace(2.0,3.0,num=4,endpoint=False,retstep=True)



print(np.linspace(5.765,10.764,40,endpoint=False,retstep=True))

(array([ 5.765   ,  5.889975,  6.01495 ,  6.139925,  6.2649  ,  6.389875,
        6.51485 ,  6.639825,  6.7648  ,  6.889775,  7.01475 ,  7.139725,
        7.2647  ,  7.389675,  7.51465 ,  7.639625,  7.7646  ,  7.889575,
        8.01455 ,  8.139525,  8.2645  ,  8.389475,  8.51445 ,  8.639425,
        8.7644  ,  8.889375,  9.01435 ,  9.139325,  9.2643  ,  9.389275,
        9.51425 ,  9.639225,  9.7642  ,  9.889175, 10.01415 , 10.139125,
       10.2641  , 10.389075, 10.51405 , 10.639025]), 0.12497499999999999)


In [29]:
# MATRIX CREATION::::::::


print("vector of Zeros",np.zeros(10))


print("\n vector of Zeros",np.zeros((8,9)))

vector of Zeros [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

 vector of Zeros [[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [36]:
print("matrix of zeros :","\n-----------------------")

print(np.zeros((5,6)))



print("\n-------------------","\n",np.ones((5,6)))



print("\n--------------------","\n",5*np.ones((5,6)))

matrix of zeros : 
-----------------------
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

------------------- 
 [[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]

-------------------- 
 [[5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5.]]


In [42]:
# construct diagonal matrix



a=np.arange(30).reshape(5,6)


print(a)


print("\n--------------------------","\n",np.arange(50).reshape(10,5))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]

-------------------------- 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]


In [52]:
# Randooom number generation::::::::


np.random.seed(6) #each number will generatte similar data


print("Random number generation (from uniform distribution) : ")

print("\n",np.random.rand(10,6))

Random number generation (from uniform distribution) : 

 [[0.89286015 0.33197981 0.82122912 0.04169663 0.10765668 0.59505206]
 [0.52981736 0.41880743 0.33540785 0.62251943 0.43814143 0.73588211]
 [0.51803641 0.5788586  0.6453551  0.99022427 0.8198582  0.41320093]
 [0.87626766 0.82375943 0.05447451 0.71863724 0.80217056 0.73640664]
 [0.70913175 0.54093685 0.12482417 0.9576473  0.4032563  0.21695116]
 [0.71727585 0.99420744 0.25561406 0.67130943 0.59900591 0.71733215]
 [0.93734953 0.35180977 0.2536341  0.40247251 0.74651072 0.72407057]
 [0.4061078  0.98937985 0.45049928 0.37380843 0.70962861 0.08245855]
 [0.39837292 0.77088097 0.76475098 0.28385938 0.18954219 0.47125096]
 [0.33480604 0.73473504 0.18910712 0.33110407 0.84422842 0.61502403]]


In [53]:
print("Numbers from normal distribution with zeroo mean and standard deviation 1 i.e. standard normal")
print(np.random.randn(10,3))

Numbers from normal distribution with zeroo mean and standard deviation 1 i.e. standard normal
[[-0.37550472  0.39636757 -0.47144628]
 [ 2.33660781  1.50278553 -0.59545972]
 [ 0.52834106  0.9398248   0.42628539]
 [-0.75815703 -0.16236698  0.72680996]
 [ 0.44408297 -0.85682264  0.44692842]
 [-1.01464799 -2.1323234   0.17386307]
 [ 0.95120126  0.44189739  1.46901739]
 [ 1.74951635  0.35353062 -0.64333729]
 [-0.04723705 -1.44903979 -0.03618977]
 [-0.09084699  0.17629034  1.09462041]]


In [57]:
print("Random integer vector:",np.random.randint(5,40,30)) #(low,high,no. of samples to be printed)



Random integer vector: [39 36  7 17 19 35 31  5 32  7  7 26  5 16 27 21 14 26 34 36 29  7 32 25
 39 10 31 27 38 38]


In [59]:
print("\n Random integer matrix :")

print(np.random.randint(1,50,(5,8)))


 Random integer matrix :
[[34 39 25 34  6 42 29 14]
 [30  3 19 12 21 43 41 40]
 [34 22  4 32 39  5 22  7]
 [ 9 42 30 24 33  4 35  8]
 [48 23  1 38 47 15 25 30]]
